### PR TITLE
Fix #225. Adapted shader alpha correction to the minimum number of sa…

### LINKED ISSUE #225: TF: opaque elements are overexposed
To reproduce: Open GUI, move right-most point gradually towards opaque. When point reaches fully opaque, the rendering "jumps" from attached image 1 -> 2 (the purple splotches).
screen shot 2015-12-16 at 11 50 54
screen shot 2015-12-16 at 11 51 08

Command line used: ```vglrun livre --volume fivox:///gpfs/bbp.cscs.ch/apps/viz/bbp/dev/BBPTestData/master/share/BBPTestData/local/simulations/may17_2011/Control/BlueConfig?target=Column,report=voltage --time 6.68 --sse 1 --camera-position 0 0 .4```

### PR DESCRIPTION
**Pull request by bilgili**
…mples

### CODE REVIEW

File: livre/eq/render/RayCastRenderer.cpp [hunk 1]
```diff
@@ -44,6 +44,8 @@ namespace livre
 
 #define glewGetContext() GLContext::glewGetContext()
 
+const uint32_t nDefaultSamplesPerRay = 512;
```
Comment (eile) [inline livre/eq/render/RayCastRenderer.cpp]: const static or move into anon namespace

File: livre/eq/render/RayCastRenderer.cpp [hunk 2]
```diff
@@ -203,6 +206,9 @@ struct RayCastRenderer::Impl
         tParamNameGL = glGetUniformLocation( program, "nSamplesPerRay" );
         glUniform1i( tParamNameGL, _computedSamplesPerRay );
 
+        tParamNameGL = glGetUniformLocation( program, "nDefaultSamplesPerRay" );
+        glUniform1i( tParamNameGL, nDefaultSamplesPerRay );
+
```
Comment (eile) [inline livre/eq/render/RayCastRenderer.cpp]: Since this can never change at runtime, is there a better way then an uniform to sync this value with the shader?

Comment (bilgili) [inline livre/eq/render/RayCastRenderer.cpp]: Not an easy one. CMake magic is needed while shader is converted into an header or improve the glshader loader to do search and replace in the shader string. I am not sure for one variable any of those worth. If more and more needed surely it can be done.

Comment (bilgili) [inline livre/eq/render/RayCastRenderer.cpp]: Additionally, speed gain is almost nothing.

**Comment by bilgili** [comment]
please retest this

**Comment by bilgili** [comment]
Retest this please.

**Comment by bilgili** [comment]
Do not merge it yet ! We have to check the alpha correction value is meaningful. @chevtche will check for it.

**Comment by bilgili** [comment]
@eile - ping

**Comment by eile** [comment]
+1
